#!/usr/bin/env bash

for d in */; do
    # Will print */ if no directories are available
    # echo "$d"
    cd $d 
    echo $(pwd)
    echo $(ls -h)
    rm -r 520 600 680 760 840 920 1000
    #for e in *; do
    #    cd $e
    #    echo $(pwd)
    #    #rm -r 440
    #    # echo $pwd
    #    cd ..
    #done
    cd ..
done
